### ISSUE TITLE
Documents Fillable Form: Requirements

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#11]
Do we have the requirements/format for fillable forms?

![2015-09-15 9-56-59 am](https://cloud.githubusercontent.com/assets/14218407/9878362/438780be-5b90-11e5-824f-5b6e42f519a9.png)

**Comment by mikebrown0** [comment]
No, the specification for this was originally targeted for mid-2016 since APEXA was responsible for making these forms fillable for everyone going live in January.  Over the last month or so, it's been decided to remove fillable forms and replace them with a contract builder inside APEXA.  The contract builder won't be available until October, so placeholder documents can just be uploaded in place of a real contracts until then.
