### ISSUE TITLE
Contract  Builder - If/Then Statements

### ISSUE THREAD

**Issue by KelsiElshaw** [ApexaCorp/feedback-portal#116]
Hi Mike,

How do I properly build if/then statements in the contract builder?
For example, I would like to build a statement that says "if the description of the rate says "override," then display the %of that rate here."

**Comment by mikebrown0** [comment]
Firstly, I'll point you at #117 since it shows how to use some shortcut syntax to avoid using a large IF statement.

Very similar to the linked issue regarding codes, you can display a single rate if you know the name of it with the following code:

```
Override Rate: @(Case.Rates.FirstOrDefault(r => r.Description == "Override") != null ? Case.Rates.FirstOrDefault(r => r.Description == "Override").Percent.ToString("p2") : "N/A")
```

The only real difference between the code example and the rate example is the value you're trying to display.  The code can be alphanumeric, so it's stored as text.  The percentage on the other hand is stored as a decimal value and needs to be converted to text in order to be displayed.

For example, let's say we have a percentage value of 1.234.  If we say:

```
Percent.ToString()
```

It will output 1.234.  That's not quite what we want especially since this is supposed to look like a percentage.  If we look a Microsoft's [Standard Numeric Format Strings](https://msdn.microsoft.com/en-us/library/dwhawy9k(v=vs.110).aspx) we learn that "p" is for percentage and then we just specify the number of decimal points to display.  If we want to display to 2 decimal points we would say:

```
Percent.ToString("p2")
```

Which will output 123.40%.  If we want 4 decimal places we would say:

```
Percent.ToString("p4")
```

Which will output 123.4000%.
