### ISSUE TITLE
Contract Builder - Accessing Items Deeper in the Data Structure

### ISSUE THREAD

**Issue by KelsiElshaw** [ApexaCorp/feedback-portal#117]
How do I display things that you have only demonstrated in the "foreach" tables.
As an example, let's say there is only 1 code number listed for a case, and I want to display the code in a sentence. I've tried @Case.code.Number, @Case.Codes.code.Number and neither works.

**Comment by mikebrown0** [comment]
If you just want to display a single code you'll need to know the name of the code.  Here is a code snipped you can paste directly into the WYSIWYG editor:

```
Life Code: @(Case.Codes.FirstOrDefault(c => c.Name == "Life") != null ? Case.Codes.FirstOrDefault(c => c.Name == "Life").Number : "N/A")
FundServ Code: @(Case.Codes.FirstOrDefault(c => c.Name == "FundServ") != null ? Case.Codes.FirstOrDefault(c => c.Name == "FundServ").Number : "N/A")
Fake Code: @(Case.Codes.FirstOrDefault(c => c.Name == "Fake") != null ? Case.Codes.FirstOrDefault(c => c.Name == "Fake").Number : "N/A")
```

This will output the following if you preview the section with some advisor data:
![image](https://cloud.githubusercontent.com/assets/1004965/10978209/a45f0136-83c3-11e5-9512-7b63bb23a4da.png)

This syntax serves as a shortcut instead of needing to do a large IF statement.  This syntax is a little verbose at the moment, but I'm working on an enhancement that will shorten it to:

```
Life Code: @(Case.Codes.FirstOrDefault(c => c.Name == "Life")?.Number ?? "N/A")
```

Expect this shorter syntax in a future version.
