### ISSUE TITLE
QUESTION: APEXA Invites not received as expected

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#139]
Hello,

Here are the details of invites that did not make it through to the destination email:

* 2015-11-06 12:27:56: Sent invite from APEXA system to CT36 using email address ct36@sunlife.com - NOT RECEIVED
* 2015-11-06 12:36:38: Sent email directly from my email to CT36@sunlife.com - RECEIVED
* 2015-11-06 12:38:32: Sent Invite from APEXA system to to CT36 using email address ct36@sunlife.com - NOT RECEIVED
* 2015-11-06 12:41:44: Sent Invite from APEXA system to to CT36 using email address jennifer.st-aubin@sunlife.com - NOT RECEIVED
* 2015-11-06 12:50:45: Sent Invite from APEXA system to to CT36 using email address jennifer.st-aubin@sunlife.ca - NOT RECEIVED
* 2015-11-06 12:52:42: Sent Invite from APEXA system to to my personal email using email address nurbur@icloud.com - RECEIVED
* 2015-11-06 13:24:01: Requested user CT36 send an email to itsupport@apexa.ca to see if this would bypass the IBM spam filtering
* 2015-11-06 13:27:33: Sent Invite from APEXA system to to CT36 using email address ct36@sunlife.com - RECEIVED

We contacted our network services and they appear to be very sure these emails never made it to slf.com as hey have no record at this very top entry level.

Thanks for looking into this,

Frank
p.s. SLF email address have .com & .ca aliases as well as fullname or code prefixes.

**Comment by mikebrown0** [comment]
Hi Frank,

I've sifted through the email logs and of the ~400 emails that have been sent since UAT opened, the only bounces that we have a record of are for fake BlueSun accounts and (what appears to be) *misspelled* variations of the Sun Life accounts you've indicated above:
![image](https://cloud.githubusercontent.com/assets/1004965/11104105/c1f8cc60-8894-11e5-9491-84f8e7063b18.png)

I also tracked down each email that you indicated above, just to make sure the email made it from the APEXA system to our email server to be sent:
* 2015-11-06 12:27:56: Sent invite from APEXA system to CT36 using email address ct36@sunlife.com - NOT RECEIVED
![image](https://cloud.githubusercontent.com/assets/1004965/11104302/de486cee-8895-11e5-8102-59ee5c535cef.png)

* 2015-11-06 12:38:32: Sent Invite from APEXA system to to CT36 using email address ct36@sunlife.com - NOT RECEIVED
![image](https://cloud.githubusercontent.com/assets/1004965/11104308/ec498cce-8895-11e5-9557-0abb9fa0886e.png)
* 2015-11-06 12:41:44: Sent Invite from APEXA system to to CT36 using email address jennifer.st-aubin@sunlife.com - NOT RECEIVED
![image](https://cloud.githubusercontent.com/assets/1004965/11104335/142cb84c-8896-11e5-8f94-6b42df0c153a.png)

* 2015-11-06 12:50:45: Sent Invite from APEXA system to to CT36 using email address jennifer.st-aubin@sunlife.ca - NOT RECEIVED
![image](https://cloud.githubusercontent.com/assets/1004965/11104347/22064d7a-8896-11e5-9823-b4616952d24f.png)

* 2015-11-06 12:52:42: Sent Invite from APEXA system to to my personal email using email address nurbur@icloud.com - RECEIVED
![image](https://cloud.githubusercontent.com/assets/1004965/11104541/587da4c4-8897-11e5-815a-0f1067b5c41e.png)

* 2015-11-06 13:27:33: Sent Invite from APEXA system to to CT36 using email address ct36@sunlife.com - RECEIVED
![image](https://cloud.githubusercontent.com/assets/1004965/11104398/78705fa2-8896-11e5-8c8f-ff188b3a4f0f.png)

Every email that was sent to a correctly spelled address appears to have been delivered, opened, and had the link inside clicked on.  Let me know if you have any other emails you'd like me to investigate.

Mike
