### ISSUE TITLE
Required Fields in Advisor Profile

### ISSUE THREAD

**Issue by IDCWIN** [ApexaCorp/feedback-portal#2]
I am adding an advisor profile on the test in-trust portal.  Please advise why these fields are mandatory and what they mean:
Contractor Id
Global Advisor Id
CIPR#

Thanks
Margaret

**Comment by mikebrown0** [comment]
The In-Trust portal is effectively a raw data editor sitting on top of the data that each carrier and MGA is providing.  As a result, the unique IDs in these data sets are required so they can be tied back to each of the partner's source systems during subsequent data imports.  The primary use case for In-Trust is for it to be populated/maintained by another system rather than being manually entered; these IDs are not user friendly, but are a necessity for the system-to-system interfaces to work.

The definition of the above fields can be found in the In-Trust file specification, which can be found [here](https://github.com/ApexaCorp/intrust-file-specification).

The CIPR number is the exception out of those 3 fields.  This is not required in the next release of In-Trust.

-Mike
