### ISSUE TITLE
BUILDER: Bullet format <> SLF Agreement Decimal Bullet Format 

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#66]
Hello,

We are unable to use decimal bullet format to mirror our current agreements:

![2015-10-29 2-12-14 pm](https://cloud.githubusercontent.com/assets/14218407/10886404/ee1fdce4-814f-11e5-97b5-e1a8753a0d60.png)

Any suggestions?

Frank

**Comment by mikebrown0** [comment]
Hi Frank,

There are really 2 ways you could choose to tackle this:

1. Create a multi-column layout with **\<div\>** tags and manually number each item.
 - If you have really odd formatting, this might be the best option.
2. Use CSS to create a list with custom numbering.

In either case, you'll have to switch to the "advanced editor" to tackle this problem; I recommend using an HTML editor and then just copying the code into the text area when you're happy with it.

I chose to go with option 2 for this example.  At first I tried to override the **\<ol\>** and **\<li\>** tags, but the PDF renderer that we're using doesn't seem to like that (it has some built in styles you can't override).  Luckily we can mimic the behavior of the **\<ol\>** and **\<li\>** tags with plain **\<div\>** tags and apply the numbers to those with CSS.  Here's the final result:

![image](https://cloud.githubusercontent.com/assets/1004965/10955993/c3cd663c-8325-11e5-8851-ee9388221269.png)

In order to do this, you can add a **\<style\>** tag to the top of your section with some custom CSS in it:

```html
<style>
    .ol-decimal {
        counter-reset: decimal-section;

        /*mimic <ol> tag css*/
        display: block;
        margin: 16px 0 16px 0;
        padding: 0 0 0 40px;
    }

        .ol-decimal > .li-decimal:before {
            counter-increment: decimal-section;
            content: counter(decimal-section) "." counter(decimal-subsection) " ";
        }

        .ol-decimal > .li-decimal > .ol-decimal {
            counter-reset: subsection;

            /*mimic <ol> tag css*/
            display: block;
            margin: 16px 0 16px 0;
            padding: 0 0 0 40px;
        }

            .ol-decimal > .li-decimal > .ol-decimal > .li-decimal:before {
                counter-increment: decimal-subsection;
                content: counter(decimal-section) "." counter(decimal-subsection) " ";
            }

    .ol-alpha {
        counter-reset: alpha-section;

        /*mimic <ol> tag css*/
        display: block;
        margin: 16px 0 16px 0;
        padding: 0 0 0 40px;
    }

        .ol-alpha > .li-alpha:before {
            counter-increment: alpha-section;
            content: "(" counter(alpha-section, lower-alpha) ")" " ";
        }

</style>
```

Once you've done that, you can use **\<div\>** tags to create your list and use the appropriate classes from the CSS to build your list.  Here's the HTML that was used to create my example PDF:

```html
<div class="list-reset">
    <div class="ol-decimal">
        <div class="li-decimal">Item</div>
        <div class="li-decimal">
            Item
            <div class="ol-decimal">
                <div class="li-decimal">Sub Item</div>
                <div class="li-decimal">
                    Sub Item
                    <div class="ol-alpha">
                        <div class="li-alpha">Sub-Sub Item</div>
                        <div class="li-alpha">Sub-Sub Item</div>
                    </div>
                </div>
                <div class="li-decimal">Sub Item</div>
            </div>
        </div>
        <div class="li-decimal">Item</div>
    </div>
</div>
```

Depending on how you want spacing and the text wrap to work you can customize this further, but this is the basis for creating a custom numbered list like the one in your example.

Let me know if you run into any issues.

Mike
